import { z } from "zod";
import { config as loadEnv } from "dotenv";
import { resolve } from "path";
import { homedir } from "os";

loadEnv();

function expandHome(p: string): string {
  return p.startsWith("~/") ? resolve(homedir(), p.slice(2)) : p;
}

const configSchema = z.object({
  telegramBotToken: z.string().min(1),
  telegramChatId: z.string().min(1),

  vaultPath: z.string().min(1).transform(expandHome),

  agentCli: z.enum(["claude", "opencode"]).default("claude"),
  agentModel: z.string().default("sonnet"),

  agentMaxTime: z.coerce.number().positive().default(7200),   // 2 hours max wall time (safety net)
  agentIdleTime: z.coerce.number().positive().default(300),   // 5 min idle = stuck
  taskConcurrency: z.coerce.number().positive().default(2),   // max parallel connector runs
  taskPollInterval: z.coerce.number().positive().default(30),
  skillExtractInterval: z.coerce.number().positive().default(3600),
  skillOrganizeInterval: z.coerce.number().positive().default(86400),
  knowledgeLintInterval: z.coerce.number().positive().default(86400),
  dashboardPort: z.coerce.number().positive().default(3120),
  brandName: z.string().default("ThinkOps"),
  brandSignature: z.string().default("— ThinkOps 🤖"),
  brandPrFooter: z.string().default("🤖 *Generated by [ThinkOps](https://github.com/dataroaring/ThinkOps) — autonomous agent pipeline*"),
});

export type Config = z.infer<typeof configSchema>;

const ENV_TO_FIELD: Record<string, string> = {
  telegramBotToken: "TELEGRAM_BOT_TOKEN",
  telegramChatId: "TELEGRAM_CHAT_ID",
  vaultPath: "VAULT_PATH",
};

export function loadConfig(): Config {
  const result = configSchema.safeParse({
    telegramBotToken: process.env.TELEGRAM_BOT_TOKEN,
    telegramChatId: process.env.TELEGRAM_CHAT_ID,
    vaultPath: process.env.VAULT_PATH,
    agentCli: process.env.AGENT_CLI,
    agentModel: process.env.AGENT_MODEL,
    agentMaxTime: process.env.AGENT_MAX_TIME,
    agentIdleTime: process.env.AGENT_IDLE_TIME,
    taskConcurrency: process.env.TASK_CONCURRENCY,
    taskPollInterval: process.env.TASK_POLL_INTERVAL,
    skillExtractInterval: process.env.SKILL_EXTRACT_INTERVAL,
    skillOrganizeInterval: process.env.SKILL_ORGANIZE_INTERVAL,
    knowledgeLintInterval: process.env.KNOWLEDGE_LINT_INTERVAL,
    dashboardPort: process.env.DASHBOARD_PORT,
    brandName: process.env.BRAND_NAME,
    brandSignature: process.env.BRAND_SIGNATURE,
    brandPrFooter: process.env.BRAND_PR_FOOTER,
  });

  if (!result.success) {
    const missing = result.error.issues.map((i) => {
      const field = String(i.path[0]);
      const envVar = ENV_TO_FIELD[field] ?? field;
      return `  ${envVar}: ${i.message}`;
    });
    console.error("\n[thinkops] Configuration error:\n");
    console.error(missing.join("\n"));
    console.error("\nCreate a .env file (see .env.example):\n");
    console.error("  cp .env.example .env");
    console.error("  # then fill in the required values\n");
    process.exit(1);
  }

  return result.data;
}
